'use client';

import { useState } from 'react';
import clsx from 'clsx';
import styles from './AiHelper.module.scss';

type Tone = 'concise' | 'friendly' | 'technical';

type AiSummaryResponse = {
  ok: boolean;
  summary?: string;
  source?: 'openai' | 'fallback';
  message?: string;
};

const toneOptions: Array<{
  value: Tone;
  label: string;
  description: string;
}> = [
  {
    value: 'concise',
    label: 'Кратко',
    description: '2-3 предложения для первого экрана.',
  },
  {
    value: 'friendly',
    label: 'Дружелюбно',
    description: 'Более живой тон для HR/команды.',
  },
  {
    value: 'technical',
    label: 'Технически',
    description: 'Акцент на стек, API и архитектуру.',
  },
];

export function AiHelper() {
  const [selectedTone, setSelectedTone] = useState<Tone>('concise');
  const [summary, setSummary] = useState('');
  const [source, setSource] = useState<'openai' | 'fallback' | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState('');

  const handleGenerate = async () => {
    setIsLoading(true);
    setError('');
    setSummary('');
    setSource(null);

    try {
      const response = await fetch('/api/ai-summary', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ tone: selectedTone }),
      });

      const data = (await response.json()) as AiSummaryResponse;

      if (!response.ok || !data.ok || !data.summary) {
        throw new Error(data.message || 'AI helper временно недоступен.');
      }

      setSummary(data.summary);
      setSource(data.source || 'fallback');
    } catch (unknownError) {
      const message =
        unknownError instanceof Error
          ? unknownError.message
          : 'Не удалось получить ответ от AI helper.';

      setError(message);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <section className="section" id="ai">
      <div className="container">
        <div className={styles.card}>
          <div className={styles.content}>
            <span className={styles.kicker}>AI integration</span>

            <h2 className="sectionTitle">
              <span className="sectionTitleAccent">AI helper</span>
            </h2>

            <p className="sectionLead">
              Небольшая AI-интеграция: генерирует краткое описание разработчика<br/>
              через AI или возвращает fallback, если ключ не настроен.
            </p>

            <div className={styles.workflow}>
              <span>GPT-4.0-mini</span>
            </div>
          </div>

          <div className={styles.demo}>
            <div className={styles.demoHeader}>
              <span className={styles.demoLabel}>live</span>
            </div>

            <div className={styles.toneGrid}>
              {toneOptions.map((option) => (
                <button
                  className={clsx(
                    styles.toneButton,
                    selectedTone === option.value && styles.toneButtonActive,
                  )}
                  key={option.value}
                  type="button"
                  onClick={() => setSelectedTone(option.value)}
                  disabled={isLoading}
                >
                  <strong>{option.label}</strong>
                  <span>{option.description}</span>
                </button>
              ))}
            </div>

            <button
              className={styles.generateButton}
              type="button"
              onClick={handleGenerate}
              disabled={isLoading}
            >
              {isLoading ? 'Генерируем...' : 'Сгенерировать описание'}
            </button>

            <div className={styles.resultBox} aria-live="polite">
              {!summary && !error && !isLoading && (
                <p className={styles.placeholder}>
                  Выберите тон и нажмите кнопку. Здесь появится результат генерации.
                </p>
              )}

              {isLoading && <p className={styles.placeholder}>AI helper обрабатывает запрос...</p>}

              {error && <p className={styles.error}>{error}</p>}

              {summary && (
                <div className={styles.success}>
                  <span>{source === 'openai' ? 'Generated by AI' : 'Fallback response'}</span>
                  <p>{summary}</p>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
